In [3]:
#menu driven 
import numpy as np

def create_1d_array():
    return np.array([1, 2, 3, 4, 5])
def create_2d_array():
    return np.zeros((3, 3))
def perform_elementwise_operations(array_a, array_b):
    result_addition = array_a + array_b
    result_subtraction = array_a - array_b
    return result_addition, result_subtraction
def print_elements_at_even_indexes(my_array):
    for i in range(0, len(my_array), 2):
        print(f"Element at index {i}: {my_array[i]}")
def calculate_sum_of_elements_2d(my_2d_array):
    return np.sum(my_2d_array)
def reshape_and_transpose_array(one_d_array):
    two_d_array = one_d_array.reshape(2, 3)
    transposed_array = np.transpose(two_d_array)
    return two_d_array, transposed_array
def generate_random_arrays():
    random_integers = np.random.randint(1, 11, size=10)
    random_floats = np.random.uniform(1,  11, size=10)
    rounded_integers = np.rint(random_floats).astype(int)
    return random_integers, rounded_integers
while True:
    print("\nMenu:")
    print("1. Create 1D array")
    print("2. Create 2D array filled with zeros")
    print("3. Perform element-wise addition and subtraction")
    print("4. Print elements at even indexes")
    print("5. Calculate sum of elements in 2D array")
    print("6. Reshape and transpose array")
    print("7. Generate random arrays")
    print("8. Exit")
    choice = int(input("Enter your choice: "))

    if choice == 1:
        print("1D Array:", create_1d_array())
    elif choice == 2:
        print("2D Array (filled with zeros):\n", create_2d_array())
    elif choice == 3:
        array_a = create_1d_array()
        array_b = create_1d_array()
        addition_result, subtraction_result = perform_elementwise_operations(array_a, array_b)
        print("Element-wise addition result:", addition_result)
        print("Element-wise subtraction result:", subtraction_result)
    elif choice == 4:
        my_array = [10, 20, 30, 40, 50, 60, 70]
        print_elements_at_even_indexes(my_array)
    elif choice == 5:
        my_2d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
        print(f"Sum of all elements: {calculate_sum_of_elements_2d(my_2d_array)}")
    elif choice == 6:
        one_d_array = create_1d_array()
        two_d_array, transposed_array = reshape_and_transpose_array(one_d_array)
        print("Original 1D array:")
        print(one_d_array)
        print("\nReshaped 2D array (shape 2x3):")
        print(two_d_array)
        print("\nTransposed array:")
        print(transposed_array)
    elif choice == 7:
        random_integers, rounded_integers = generate_random_arrays()
        print("Random integers:", random_integers)
        print("Rounded integers:", rounded_integers)
    elif choice == 8:
        print("Exiting the program. Goodbye!")
        break
    else:
        print("Invalid choice. Please select a valid option.")


Menu:
1. Create 1D array
2. Create 2D array filled with zeros
3. Perform element-wise addition and subtraction
4. Print elements at even indexes
5. Calculate sum of elements in 2D array
6. Reshape and transpose array
7. Generate random arrays
8. Exit
1D Array: [1 2 3 4 5]

Menu:
1. Create 1D array
2. Create 2D array filled with zeros
3. Perform element-wise addition and subtraction
4. Print elements at even indexes
5. Calculate sum of elements in 2D array
6. Reshape and transpose array
7. Generate random arrays
8. Exit
2D Array (filled with zeros):
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Menu:
1. Create 1D array
2. Create 2D array filled with zeros
3. Perform element-wise addition and subtraction
4. Print elements at even indexes
5. Calculate sum of elements in 2D array
6. Reshape and transpose array
7. Generate random arrays
8. Exit
Element-wise addition result: [ 2  4  6  8 10]
Element-wise subtraction result: [0 0 0 0 0]

Menu:
1. Create 1D array
2. Create 2D array filled with zeros

ValueError: cannot reshape array of size 5 into shape (2,3)