In [1]:
#create a 1D array with elements from 1 to 5. also create a 2D array with shape (3,3) filled with zeros 
import numpy as np
one_d_array = np.array([1, 2, 3, 4, 5])
print("1D Array:", one_d_array)
two_d_array = np.zeros((3, 3))
print("2D Array (filled with zeros):\n", two_d_array)


1D Array: [1 2 3 4 5]
2D Array (filled with zeros):
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
