In [1]:
#create a 1D array and reshape the array with shape (2,3). transpose the array 
import numpy as np
one_d_array = np.array([1, 2, 3, 4, 5, 6])
two_d_array = one_d_array.reshape(2, 3)
transposed_array = np.transpose(two_d_array)
print("Original 1D array:")
print(one_d_array)
print("\nReshaped 2D array (shape 2x3):")
print(two_d_array)
print("\nTransposed array:")
print(transposed_array)

Original 1D array:
[1 2 3 4 5 6]

Reshaped 2D array (shape 2x3):
[[1 2 3]
 [4 5 6]]

Transposed array:
[[1 4]
 [2 5]
 [3 6]]
